services:
  - type: web
    name: projek-study
    env: php
    plan: free
    buildCommand: |
      cp .env.example .env
      composer install --no-dev --optimize-autoloader --no-scripts --ignore-platform-reqs
      php artisan key:generate
      php artisan migrate --force
      php artisan config:cache
      npm install
      npm run build
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
